/**
 *
 * Idea: The components don't have to use hooks that query data when state changes.
 * We should use observables.
 *
 * How to do ComponentDidMount???
 */

import { NextPage } from 'next'
import Container from 'src/components/atoms/Container'
import ProductPage from 'src/components/templates/ProductPage'
import { NextSeo } from 'next-seo'
import Head from 'next/head'
import { Style } from 'src/generated/graphql'

const PreviewHome: NextPage = () => (
  <>
    {' '}
    <Head>
      <title>Previewing new home | Zillow clone - Karthick Ragavendran</title>
      <meta name='description' content='Generated by create next app' />
      <meta name='viewport' content='width=device-width, initial-scale=1' />
      <link rel='icon' href='/favicon.ico' />
    </Head>
    <Container>
      <ProductPage
        home={{
          fetching: false,
          stale: false,
          data: {
            property: {
              id: 12,
              priceSqft: 12,
              createdAt: '2020-01-01',
              updatedAt: '2020-01-01',
              address:
                '6046 M J Taylor Road, Hahira, Georgia 31632, United States',
              bath: 1,
              beds: 1,
              city: 'Hahira',
              description: 'Goood house.',
              facts: '',
              features: 'yes.',
              lat: 31.03866,
              lng: -83.45001,
              lotSize: 1200,
              price: 878,
              sqft: 1000,
              state: 'Georgia',
              style: Style.SingleFamilyHome,
              yearBuilt: 1999,
              zipcode: '31632',
              imgs: [],
            },
          },
        }}
      />
    </Container>
  </>
)

export default PreviewHome
