import type { GetStaticProps, NextPage } from 'next'
import Head from 'next/head'
import { NextSeo } from 'next-seo'
import React from 'react'
import Home from 'src/components/templates/Home'

export const getStaticProps: GetStaticProps = async () => ({
  props: { data: ['Karthick', 'Ragavendran'] }, // will be passed to the page component as props
})

/**
 * How to infer getStaticProps type?
 * {}: InferGetStaticPropsType<typeof getStaticProps>
 */

const HomePage: NextPage = () => (
  <div>
    <NextSeo
      title='🏡 Zillow - Refactor'
      description='A short description goes here which says what goes here.'
    />
    <Head>
      <title>Zillow - Refactor</title>
      <meta name='description' content='Generated by create next app' />
      <link rel='icon' href='/favicon.ico' />
    </Head>
    <Home />
  </div>
)

export default HomePage
