import type { NextPage } from 'next'
import Head from 'next/head'
import { NextSeo } from 'next-seo'
import Home from 'src/components/templates/Home'

const HomePage: NextPage = () => (
  <div>
    <NextSeo
      title='🏡 Zillow - Refactor'
      description='A short description goes here which says what goes here.'
    />
    <Head>
      <title>Zillow - Refactor</title>
      <meta name='description' content='Generated by create next app' />
      <link rel='icon' href='/favicon.ico' />
    </Head>
    <Home />
  </div>
)

export default HomePage
